### ISSUE TITLE
Cups service name has changed.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/install-scripts#20]
Hello.

Since November 20th, 2020, cups service is no longer `org.cups.cupsd` but `cups.service`.

Archlinux commit: https://github.com/archlinux/svntogit-packages/commit/104686c89c71b81d40e07bc92bb7c70264de3d88#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

So you need to modify chrooted_cleaner_script.sh in line 87. Replace:

`local _systemd_enable=(NetworkManager vboxservice org.cups.cupsd avahi-daemon systemd-timesyncd tlp gdm lightdm sddm) `
by

`local _systemd_enable=(NetworkManager vboxservice cups avahi-daemon systemd-timesyncd tlp gdm lightdm sddm)`

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/install-scripts/commit/9f677cc6ce46cfc483fd721b5d40f5f1931c5d80
done
