### ISSUE TITLE
Network check can not work in some country .

### ISSUE THREAD

**Issue by doublehou** [endeavouros-team/install-scripts#24]
becuase of IPS's contols,(can't visit github.com ), network check say not online , but can connet the internet . 
may give some alternative  website address to check ?

**Comment by killajoe** [comment]
If you can not access GitHub netinstall will not work for you.
You can only use offline install.

**Comment by doublehou** [comment]
> 
> 
> If you can not access GitHub netinstall will not work for you.
> You can only use offline install.

oh,I got it , not only check network using github.com .  thanks anyway .

**Comment by killajoe** [comment]
We may change this in the future, but it will need to have our Git stuff handled by mirrors, to get it working global, otherwise, it will be the same ;)
